name: Run Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MAILERLITE_COOKIE: ${{ secrets.MAILERLITE_COOKIE }}
      MAILINATOR_DOMAIN: ${{ secrets.MAILINATOR_DOMAIN }}
      MAILINATOR_API_KEY: ${{ secrets.MAILINATOR_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
         path: ~/.m2/repository
         key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
         restore-keys: ${{ runner.os }}-maven

      - name: Set up Chrome and ChromeDriver
        uses: browser-actions/setup-chrome@v1

      - name: Run Maven tests
        run: mvn clean test
