name: Run Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MAILERLITE_COOKIE: ${{ secrets.MAILERLITE_COOKIE }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Install ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromedriver

      - name: Run Maven tests
        run: mvn clean test
