name: Run Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MAILERLITE_COOKIE: ${{ secrets.MAILERLITE_COOKIE }}
      MAILINATOR_DOMAIN: ${{ secrets.MAILINATOR_DOMAIN }}
      MAILINATOR_API_KEY: ${{ secrets.MAILINATOR_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Set up Chrome and ChromeDriver
        uses: browser-actions/setup-chrome@v1

      - name: Run Maven tests
        run: mvn clean test
