name: Spotless Check

on:
  push:
    branches:
      - '**'

jobs:
  spotless:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Run Spotless Check
        run: mvn spotless:check

      - name: Fail if Spotless finds issues
        run: |
          echo "::error file=Spotless found issues. Run mvn spotless:apply to fix them."
        if: failure()
